---
title: "Ecoli Genome Analysis"
author: "Kathleen Wang"
date: "October 12, 2015"
output: html_document
---

#Here I'm working with the data carpentry ecoli genomes data set. Found at http://tracykteal.github.io/R-genomics/02-starting-with-data.html on October 12 at 1:26 PM

```{r set seed, echo = TRUE, eval=TRUE}
set.seed(40147562)
```

#Below I'm importing the **ecoli data** from the data folder
```{r {r Import Data, echo = TRUE, eval = TRUE}}
metadata <- read.csv('data/Ecoli_metadata.csv') ##reading in data file into an object named "metadata""
##View(metadata) ##looking at table within R
head(metadata) ##looking at first 6 rows of dataframe
str(metadata) ##looking structure of data
## ?str ##help page on str
## ??str ##all help pages with "str" in it
mean(metadata$genome_size) ##calculating the mean
```

```{r {r package import, echo = TRUE, eval = TRUE}
##install.packages("ggplot2") ##Install the best plotting package in R
library("ggplot2"") ##Make sure R knows to source from it
```

```r{ {r data exploration, echo = TRUE, eval = TRUE, fig.center = TRUE}}
##Plot 1: looking at distribution of genome size
ggplot(metadata, aes(x = genome_size)) +
  geom_bar(stat = "bin", binwidth=0.01) # create a bar plot (histogram) with bins by a genome size of 0.01
```